# These are supported funding model platforms

github: [mckaygerhard, mckayshirou, vegnuli] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: [mckaygerhard]# Replace with a single Ko-fi username
liberapay: [mckaygerhard]# Replace with a single Liberapay username
